### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by doliverio** [storyblok/storyblok-angular-example#2]
### Subject of the issue
Error when building the project

### Environment

    $ ng -v
    Angular CLI: 6.0.8
    Node: 10.7.0
    OS: darwin x64
    Angular: 6.0.7

### Steps to reproduce

    git clone https://github.com/storyblok/storyblok-angular-example.git
    npm install
    ng build --prod

### Expected behaviour
Successful build

### Actual behaviour
``
ERROR in src/app/app.component.html(4,10): : Property 'content' does not exist on type 'string'.
src/app/app.component.html(9,8): : Property 'name' does not exist on type 'string'.
src/app/feature/feature.component.html(1,6): : Property '_editable' does not exist on type 'FeatureComponent'.
``

**Comment by onefriendaday** [comment]
Thanks for the report!

Has been fixed in commit https://github.com/storyblok/storyblok-angular-example/commit/7e7af07af1ff0b43e6125f3a019a9d1b00db3f12
